# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bank.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='bank.proto',
  package='bank',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\nbank.proto\x12\x04\x62\x61nk\"G\n\x11\x63lientRequestRead\x12\n\n\x02ID\x18\x01 \x01(\x05\x12\x11\n\tInterface\x18\x02 \x01(\t\x12\x13\n\x0bLastEventID\x18\x03 \x01(\x03\"W\n\x12\x63lientRequestWrite\x12\n\n\x02ID\x18\x01 \x01(\x05\x12\x11\n\tInterface\x18\x03 \x01(\t\x12\r\n\x05Money\x18\x04 \x01(\x03\x12\x13\n\x0bLastEventID\x18\x05 \x01(\x03\"V\n\x0e\x62ranchResponse\x12\n\n\x02ID\x18\x02 \x01(\x05\x12\x0f\n\x07\x42\x61lance\x18\x01 \x01(\x03\x12\x0e\n\x06Status\x18\x03 \x01(\t\x12\x17\n\x0f\x41ssignedEventID\x18\x04 \x01(\x05\"e\n\rBranchRequest\x12\n\n\x02ID\x18\x01 \x01(\x05\x12\x17\n\x0f\x41ssignedEventID\x18\x02 \x01(\x05\x12\x11\n\tInterface\x18\x03 \x01(\t\x12\r\n\x05Money\x18\x04 \x01(\x03\x12\r\n\x05\x43lock\x18\x05 \x01(\x05\"3\n\x0eupdateResponse\x12\x11\n\tBResponse\x18\x01 \x01(\t\x12\x0e\n\x06\x42\x43lock\x18\x02 \x01(\x05\x32\xc6\x01\n\x06\x63reate\x12@\n\x0fMsgDeliveryRead\x12\x17.bank.clientRequestRead\x1a\x14.bank.branchResponse\x12\x42\n\x10MsgDeliveryWrite\x12\x18.bank.clientRequestWrite\x1a\x14.bank.branchResponse\x12\x36\n\tpropagate\x12\x13.bank.BranchRequest\x1a\x14.bank.updateResponseb\x06proto3'
)




_CLIENTREQUESTREAD = _descriptor.Descriptor(
  name='clientRequestRead',
  full_name='bank.clientRequestRead',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ID', full_name='bank.clientRequestRead.ID', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Interface', full_name='bank.clientRequestRead.Interface', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='LastEventID', full_name='bank.clientRequestRead.LastEventID', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=91,
)


_CLIENTREQUESTWRITE = _descriptor.Descriptor(
  name='clientRequestWrite',
  full_name='bank.clientRequestWrite',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ID', full_name='bank.clientRequestWrite.ID', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Interface', full_name='bank.clientRequestWrite.Interface', index=1,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Money', full_name='bank.clientRequestWrite.Money', index=2,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='LastEventID', full_name='bank.clientRequestWrite.LastEventID', index=3,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=93,
  serialized_end=180,
)


_BRANCHRESPONSE = _descriptor.Descriptor(
  name='branchResponse',
  full_name='bank.branchResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ID', full_name='bank.branchResponse.ID', index=0,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Balance', full_name='bank.branchResponse.Balance', index=1,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Status', full_name='bank.branchResponse.Status', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='AssignedEventID', full_name='bank.branchResponse.AssignedEventID', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=182,
  serialized_end=268,
)


_BRANCHREQUEST = _descriptor.Descriptor(
  name='BranchRequest',
  full_name='bank.BranchRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ID', full_name='bank.BranchRequest.ID', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='AssignedEventID', full_name='bank.BranchRequest.AssignedEventID', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Interface', full_name='bank.BranchRequest.Interface', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Money', full_name='bank.BranchRequest.Money', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Clock', full_name='bank.BranchRequest.Clock', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=270,
  serialized_end=371,
)


_UPDATERESPONSE = _descriptor.Descriptor(
  name='updateResponse',
  full_name='bank.updateResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='BResponse', full_name='bank.updateResponse.BResponse', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='BClock', full_name='bank.updateResponse.BClock', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=373,
  serialized_end=424,
)

DESCRIPTOR.message_types_by_name['clientRequestRead'] = _CLIENTREQUESTREAD
DESCRIPTOR.message_types_by_name['clientRequestWrite'] = _CLIENTREQUESTWRITE
DESCRIPTOR.message_types_by_name['branchResponse'] = _BRANCHRESPONSE
DESCRIPTOR.message_types_by_name['BranchRequest'] = _BRANCHREQUEST
DESCRIPTOR.message_types_by_name['updateResponse'] = _UPDATERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

clientRequestRead = _reflection.GeneratedProtocolMessageType('clientRequestRead', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTREQUESTREAD,
  '__module__' : 'bank_pb2'
  # @@protoc_insertion_point(class_scope:bank.clientRequestRead)
  })
_sym_db.RegisterMessage(clientRequestRead)

clientRequestWrite = _reflection.GeneratedProtocolMessageType('clientRequestWrite', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTREQUESTWRITE,
  '__module__' : 'bank_pb2'
  # @@protoc_insertion_point(class_scope:bank.clientRequestWrite)
  })
_sym_db.RegisterMessage(clientRequestWrite)

branchResponse = _reflection.GeneratedProtocolMessageType('branchResponse', (_message.Message,), {
  'DESCRIPTOR' : _BRANCHRESPONSE,
  '__module__' : 'bank_pb2'
  # @@protoc_insertion_point(class_scope:bank.branchResponse)
  })
_sym_db.RegisterMessage(branchResponse)

BranchRequest = _reflection.GeneratedProtocolMessageType('BranchRequest', (_message.Message,), {
  'DESCRIPTOR' : _BRANCHREQUEST,
  '__module__' : 'bank_pb2'
  # @@protoc_insertion_point(class_scope:bank.BranchRequest)
  })
_sym_db.RegisterMessage(BranchRequest)

updateResponse = _reflection.GeneratedProtocolMessageType('updateResponse', (_message.Message,), {
  'DESCRIPTOR' : _UPDATERESPONSE,
  '__module__' : 'bank_pb2'
  # @@protoc_insertion_point(class_scope:bank.updateResponse)
  })
_sym_db.RegisterMessage(updateResponse)



_CREATE = _descriptor.ServiceDescriptor(
  name='create',
  full_name='bank.create',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=427,
  serialized_end=625,
  methods=[
  _descriptor.MethodDescriptor(
    name='MsgDeliveryRead',
    full_name='bank.create.MsgDeliveryRead',
    index=0,
    containing_service=None,
    input_type=_CLIENTREQUESTREAD,
    output_type=_BRANCHRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='MsgDeliveryWrite',
    full_name='bank.create.MsgDeliveryWrite',
    index=1,
    containing_service=None,
    input_type=_CLIENTREQUESTWRITE,
    output_type=_BRANCHRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='propagate',
    full_name='bank.create.propagate',
    index=2,
    containing_service=None,
    input_type=_BRANCHREQUEST,
    output_type=_UPDATERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CREATE)

DESCRIPTOR.services_by_name['create'] = _CREATE

# @@protoc_insertion_point(module_scope)
